[[plugins]]
package = "@netlify/plugin-sitemap"
[build]
  publish = "dist"  # Change this to your actual publish folder (e.g., "public", "build", etc.)

[[redirects]]
  from = "/categories/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/products/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
