// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttwhalhtwbwrplnwzyvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0d2hhbGh0d2J3cnBsbnd6eXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NDI1NTUsImV4cCI6MjA2NzIxODU1NX0.ipn4vBipoVBQmBKc4dsTstk76l_WIcK9a09HTer3o4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});